[project]
name = "yeti"
version = "0.1.0"
description = "ETL platform"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-include-markdown-plugin>=7.2.0",
    "mkdocs-material>=9.6.21",
    "mkdocs-mermaid2-plugin>=1.2.2",
]
