services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.7
    restart: always
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  kafka:
    image: confluentinc/cp-kafka:7.7.7
    restart: always
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_BROKER_ID=1
      - KAFKA_JMX_PORT=7071
      - KAFKA_JMX_HOSTNAME=kafka
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "9092:9092"
      - "7071:7071"
    depends_on:
      - zookeeper
    networks:
      - kafka_network

  init-topics:
    image: confluentinc/cp-kafka:7.7.0
    restart: "no"
    environment:
      BOOTSTRAP_SERVER: kafka:9092
      KAFKA_DEFAULT_PARTITIONS: 0
      KAFKA_DEFAULT_REPLICATION: 0
      KAFKA_TOPICS: ${KAFKA_TOPICS:-input_events,filtered_events,deduplicated_events,processed_events,config_updates,system_dlq}
    volumes:
      - ${PWD}/scripts/init-topics.sh:/init-topics.sh:ro
    entrypoint: ["/bin/bash", "/init-topics.sh"]
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka_network

  jmx_exporter:
    build:
      context: ${PWD}
      dockerfile: ${PWD}/deployments/jmx/Dockerfile
    restart: always
    ports:
      - "5556:5556"
    volumes:
      - ${PWD}/config/kafka/jmx_config.yml:/etc/jmx-exporter/config.yml:ro
    environment:
      JMX_PORT: 5556
      JMX_CONFIG: /etc/jmx-exporter/config.yml
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O- http://localhost:5556/metrics > /dev/null || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge
